FROM matthewcmead/anaconda-nb-docker-centos7 as builder

# Superset version
ARG SUPERSET_VERSION=0.26.3

# Configure environment
ENV LANG=en_US.utf8 \
    LC_ALL=en_US.utf8 \
    PYTHONPATH=/etc/superset:/home/superset:$PYTHONPATH \
    SUPERSET_VERSION=${SUPERSET_VERSION} \
    SUPERSET_HOME=/var/lib/superset

RUN \
    touch /tmp/install_timestamp \
&&  sed -i "s/override_install_langs=en_US.UTF-8/override_install_langs=en_US.utf8/g" /etc/yum.conf \
&&  yum groups mark install "Development Tools" \
&&  yum groups mark convert "Development Tools" \
&&  yum groupinstall -y 'Development Tools' \
&&  yum install -y \
      cyrus-sasl-devel \
      openldap-devel \
      mariadb-devel \
      postgresql-devel \
      libffi-devel

COPY pips /project/pips

#RUN pip install --no-cache-dir --no-index --find-links /project/pips \
#        setuptools==40 \
#        pip==10.0.1 || echo "uninstall might fail"

RUN pip install --no-cache-dir --no-index --find-links /project/pips \
        -r /project/pips/requirements.txt \
        Werkzeug==0.12.1 \
        flask-cors==3.0.3 \
        flask-mail==0.9.1 \
        flask-oauth==0.12 \
        flask_oauthlib==0.9.3 \
        gevent==1.2.2 \
        impyla==0.14.0 \
        mysqlclient==1.3.7 \
        psycopg2==2.6.1 \
        pyhive==0.5.1 \
        pyldap==2.4.28 \
        redis==2.10.5 \
        superset==${SUPERSET_VERSION}

#RUN  mkdir /conda_overlay \
#&&   (cd /opt && find conda -type f -newer /tmp/install_timestamp >/tmp/conda_changed.txt) \
#&&   tar -C /opt --files-from /tmp/conda_changed.txt -cf - | tar -C /conda_overlay -xf -

FROM centos:7 as runner

# Superset version
ARG SUPERSET_VERSION=0.26.3

# Configure environment
ENV PATH /opt/conda/bin:$PATH
ENV LANG=en_US.utf8 \
    LC_ALL=en_US.utf8 \
    PYTHONPATH=/etc/superset:/home/superset:$PYTHONPATH \
    SUPERSET_VERSION=${SUPERSET_VERSION} \
    SUPERSET_HOME=/var/lib/superset

RUN \
    yum install -y \
      wget \
      bzip2 \
      ca-certificates \
      glib2 \
      libXext \
      libSM \
      libXrender \
      git \
      mercurial \
      subversion \
      curl \
      grep \
      sed \
      cyrus-sasl-devel \
      openldap-devel \
      mariadb-devel \
      postgresql-devel \
      libffi-devel \
&& \
    yum clean all

RUN echo 'export PATH=/opt/conda/bin:$PATH' > /etc/profile.d/conda.sh

COPY --from=builder /opt/conda /opt/conda
COPY --from=builder /tini /tini

RUN chmod 755 /tini

RUN useradd -b /home -U -m superset && \
    mkdir /etc/superset && \
    mkdir /etc/superset/db && \
    chown -R superset:superset /home/superset /etc/superset

RUN mkdir /var/lib/superset && chown -R superset:superset /var/lib/superset

# Configure Filesystem
COPY superset /usr/local/bin
VOLUME /home/superset \
       /etc/superset \
       /var/lib/superset
WORKDIR /home/superset

# Deploy application
EXPOSE 8088
HEALTHCHECK CMD ["curl", "-f", "http://localhost:8088/health"]
ENTRYPOINT [ "/tini", "--" ]
CMD ["/usr/local/bin/superset-start"]
USER superset
