version: '3'
services:
  redis:
    image: matthewcmead/redis-centos7
    restart: unless-stopped
    volumes:
      - redis:/data
  superset:
    image: matthewcmead/superset-centos7
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
    ports:
      - "8088:8088"
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py
      - superset_db:/var/lib/superset
  worker:
    image: matthewcmead/superset-centos7
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py
      - superset_db:/var/lib/superset
    command: superset worker
volumes:
  redis:
    external: false
  superset_db:
    external: false
