#!/usr/bin/env bash

db="/var/lib/superset/superset.db"
if [ ! -e "$db" ]; then
  touch "$db"
fi

exec gunicorn -w 2 --timeout 60 -b 0.0.0.0:8088 --limit-request-line 0 --limit-request-field_size 0 superset:app
